refactor: user 추가 로직 변경
se-gam/segam-backend pull request #16
Opened 2024-02-26 15:40 UTC by RightHennessy

user 테이블 변경에 따라 이와 관련된 모든 로직이 업데이트 되었습니다.

2024-02-26 15:49 UTC, therealjamesjung requested changes
저 빈 if만 처리하면 나머진 조와보입니다!

2024-02-26 15:49 UTC, therealjamesjung commented on src/studyroom/studyroom.service.ts
> +      if (error.status === 400) {
오잉 이거 왜 비어있죠?!

2024-02-26 15:49 UTC, therealjamesjung commented on src/studyroom/studyroom.service.ts
> +      if (error.status === 400) {
이거는 그냥 DB 쿼리에서 던지는 오류를 잡는 곳 같은데 그냥 아예 try catch 없어도 되지 않나용?!

2024-02-27 02:36 UTC, RightHennessy commented on src/studyroom/studyroom.service.ts
> +      if (error.status === 400) {
db는 아니고.. 함수 재활용 하려고 하다보니 이렇게 됐습니다..
 그냥 함수 분리 해줬습니다.

2024-02-27 02:40 UTC, therealjamesjung approved these changes
아주 좋습니당

2024-02-27 04:53 UTC, merged