feat: 스터디룸 api
se-gam/segam-backend pull request #6
Opened 2024-02-14 11:55 UTC by RightHennessy

스터디룸 쪽 api 만드는 도중 중간 점검 올립니다. (02-14)

### 진행 상황

- [x] 스터디룸 전체 조회
- [x] 스터디룸 개별 조회
- [ ] 스터디룸 예약
- [ ] 스터디룸 취소
- [x] 스터디룸 예약 목록 
- [ ] 스터디룸 초대 가능 확인
- [ ] 스웨거 달기

아직 웹에서 직접 취소한 예약은 반영을 안한 상태입니다~

### db 변경점

studyroomReservation에 pid 추가하고(unique 아님..), id를 booking_id로 부여하기로 했습니다.
(-> studyroom의 pid로 지정해야할까요.. booking_pid길래 studyroomReservatoin에 지정했는데 데이터를 보니 스터디룸 별 고유 id 같더라고요)

user 테이블에서 pid를 nullable로 바꿨습니다.

### 로직 변경점

크롤링하여 slot update 하는 부분을 upsert 하도록 변경하였습니다.

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/dto/studyroomslot.dto.ts
> +  static from(slots: StudyroomSlot[]): StudyroomSlotDto[] {
이거만 따로 타입을 만들어주지 않고, Prisma가 생성해준 타입을 사용하는 이유가 있나요?

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/query/studyroom.query.ts
> +}
요것들 필요한거면 변수뒤에 ! 붙히고, Optional이면 ?붙혀야 할 것 같아용
근데 싹 다 옵셔널로 하기로 논의된거 아닌가요?

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/reservation.service.ts
> +        process.env.RESERVATION_URL,
이거는 RESERVATION_URL에다가 Post를 하는 것이 새로운 Reservation을 생성하는 느낌이네용
변수명을 GET_USER_RESEVATIONS_URL 같은 느낌으로 바꾸는게 조와보입니다

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +              lt: query.timeLte,
변수명을 lt로 바꾸던지, 쿼리를 lte로 하던지 하는게 좋을 것 같습니당

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +      where: {
deletedAt 옵션 빠짐!

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +      where: {
여기도 deletedAt

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +  async getReservations(userId: string): Promise<StudyroomReservation[]> {
이쪽 부분은 쿼리를 전체적으로 같이 고쳐봅시다.. 지금 식이라면 DB가 많이 아파할꺼에요.
웬만하면 네트워크 오버로드를 줄이기 위해서 한번의 DB커넥션으로 DB작업을 다 끝내버리는게 좋아요. 특히 Promise.all()로 동시에 여러 요청을 DB에 떄리면 과금폭탄, 심한경우 DB가 다운될 수도 있습니당.

이 함수에 있는 모든 내용을 일단 한 트랜잭션 안에서 끊고, 많은 것들을 join쿼리 같은거를 써서 받아올 수 있습니다. 차근차근 생각해야해서 같이 켜놓고 고민해봅시당. 일단은 이 부분 제외하고 나머지 다 한 뒤에 같이 쿼리를 최적화해보시죵

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +  async updateReservations(
요기도 마찬가지!

2024-02-14 12:36 UTC, therealjamesjung commented on src/studyroom/studyroom.service.ts
> +    const upsertSlots = studyRooms.flatMap((rawStudyroom) => {
이쪽은 의도한 대로 잘 작동하나요..? upsert에 대한 의구심이 살짝..
DB를 조회해서 해당 id가 있는지 찾고, 있으면 업데이트하고, 없으면 생성하는게 이거 한방에 되나용..?

transaction하나 열어서 거기 안에서 처리하는게 어떨까요?

2024-02-14 12:36 UTC, therealjamesjung commented on src/user/payload/UserInfoPayload.payload.ts
> +  student_id!: string;
이거는 백엔드에서 사용하는 변수라 studentId로 가시죠

2024-02-14 12:39 UTC, therealjamesjung commented
트랜잭션 관련한 내용은 여기 참고하면 좋습니다

https://www.prisma.io/docs/orm/prisma-client/queries/transactions#interactive-transactions

2024-02-14 13:41 UTC, RightHennessy commented on src/studyroom/query/studyroom.query.ts
> +}
ㅋㅋㅋㅋㅋㅋ 다른거 고치다가 뒤로가기한 상태로 커밋햇네요...ㅎ

2024-02-14 13:44 UTC, RightHennessy commented on src/studyroom/studyroom.repository.ts
> +              lt: query.timeLte,
오.. 섬세하시네요.. lt로 변경하였습니다

2024-02-17 16:08 UTC, RightHennessy commented
### 진행 상황

스터디룸 예약만 마무리 하면됩니다 ~

- [ ] 스터디룸 예약 (검토 필요)
- [x] 스터디룸 취소
- [x] 스터디룸 예약 목록 (온라인 취소까지 반영)
- [x] 스터디룸 초대 가능 확인
- [x] 스웨거 달기

### db 변경점

studyroomReservation에 studyroomId, deletedAt 추가하였습니다.

### 로직 변경점

위 리뷰들은 모두 반영하였습니다.

updateReservation 로직 변경이 있으나 최적화가 된지는 의문입니다. 이쪽 확인 부탁드립니다 ~

2024-02-17 16:09 UTC, RightHennessy commented on src/studyroom/studyroom.service.ts
> +    const upsertSlots = studyRooms.flatMap((rawStudyroom) => {
upsert를 transaction 내에서 처리하게 했습니다. 👍

2024-02-18 12:27 UTC, therealjamesjung requested changes
고생이 많으십니다.. 코멘트 드린 부분들 한번 더 생각해보면서 조금만 더 고치면 되게 좋을 것 같습니다 음하하.

Reservation Service를 분리한 부분이 아주 좋네여

더 고쳤으면 좋겠다고 생각 되는 부분은
1. Studyroom Service에서 Reservation Service의 반환값에 따라 적절하게 에러를 받아서 프론트에 전달하기
2. Type과 DTO의 확실한 분리
  - Type은 Service와 Repository에서 사용하는 내부 타입들
  - DTO는 Service에서 Controller로 내보낼 때 가장 Type 데이터를 갖고 `from`함수에서 유저에게 보여줄 데이터 가공해서 반환

요정도 입니다!
최고네요 👍

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/dto/studyroom.dto.ts
> +  @ApiProperty({
가독성을 위해 각 필드 사이 간격을 하나씩 띄우는건 어떨까요~!

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/dto/studyroomReservation.dto.ts
> +        .sort((a, b) => {
이건 어떤 기준으로 정렬이 되나요?

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/payload/studyroomReserve.payload.ts
> +    description: '날짜',
요것는 날짜 예시값을 주는게 좋을 것 같아여

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/payload/studyroomReserve.payload.ts
> +  @Type(() => Number)
이런식으로 모든 string을 Number를 강제로 형변환하는 이유가 있나요?

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/query/studyroom.query.ts
> +    description: '인원수(deafult: 3)',
오타걸~ (x4)

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/types/studyroomReservation.type.ts
> +export class StudyroomReservation {
DTO인데 타입에 들어가있네요!

2024-02-18 12:27 UTC, therealjamesjung commented on src/user/payload/UserInfoPayload.payload.ts
> +  static from(password: string) {
페이로드도 from 함수가 필요없을 것 같아요!

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +      return StudyroomReservation.from(userId, reservation);
Repository는 정말 DB에서 정제되지 않은 데이터를 받아오기만 하는 곳으로 역할을 분리했기 때문에, 이 작업들은 Repository에서 하지 말고 Service에서 하는 것이 좋습니당

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/reservation.service.ts
> +    if (rawUsers.length != payload.users.length)
`!==` !!

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/dto/studyroomReservation.dto.ts
>  export class StudyroomReservatoinListDto {
오타걸~

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/studyroom.service.ts
> +      process.env.CRAWLER_API_ROOT + '/calendar',
요기도 configService로 바꿔주세용

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/studyroom.service.ts
> +
요기 아래 3개는 반환값이 없네요?! 오류가 나면 유저에게도 오류를 전달해주는게 좋을 것 같습니다

가령, "이미 그 날짜에 추가한 친구가 이미 예약된 경우, `{"error": "﻿동반이용자를 잘못입력하셨습니다. 중복으로 예약할 수 없습니다."}` 같은 메세지가 서버에서 오기 때문에 이것들을 그대로 프론트로 전달해주는게 조와보입니다

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/studyroom.service.ts
> +      UserInfoPayload.from(payload.password),
이렇게 한 이유는 무엇인가요?!

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/studyroom.service.ts
> +    await this.studyroomRepository.cancelReservation(id, payload.cancelReason);
위에 두개는 이름이 똑같은 함수인데 하는 일은 다른 것 같아서, 다른 이름을 고민해보는건 어떨까요?
repository는 우리 DB니까 delete라던지..

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
Repository 함수들에도 각각 Return 타입을 지정해주세요!

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +  async createReservations(
transaction을 이어받아서 쿼리하는 함수라면 무조건 이 repository에서 호출하기 때문에 private하는게 좋지 않을까요?

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/reservation.service.ts
>        if (error.response.status == 401) {
`===` !!

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/reservation.service.ts
> +      if (error.response.status == 400) {
`===` !!

2024-02-18 12:27 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +  async deleteReservations(userId: string, reservations: ReservationResponse) {
단순히 DB에서 deletedAt만 업데이트 해주는거라면 트랜잭션으로 열 필요가 있을까요?
ManyToMany 관계에 있는 테이블에서 쿼리를 시작하는 것이 대부분 쿼리를 헷갈리게 만들긴 합니다
저는 보통 쿼리를 짤때 이런 사고 흐름으로 짜는데 한번 생각해보셔요

이 함수의 경우에는
1. 유저아이디를 받아서
2. 그 사람이 한 예약중에 reservationIds안에 있는 Reservation만 삭제한다

라는 목표를 세팅한 뒤에 삭제해야하는 대상 테이블부터 쿼리를 시작합니다. 지금의 경우에는 `studyroomReservation`이겠네용
그래서 예약을 한 사람들에서 필터를 걸어야 하기 때문에 `users`를 타서 거기에서 유저 아이디와 비교를 우선 하고, 적절하게 시간이나 `IsLeader`같은 것들을 필터링 합니다. 이렇게 `studyroomReservation`들이 필터링이 됐다면 업데이트 하고 싶은 값들을 지정하면 됩니다. 우리의 경우에는 users의 deletedAt과, slots의 deletedAt를 업데이트 해줘야겠네요

이렇게 한다면 트랜잭션안에서 여러 쿼리를 나눠서 치는 것이 아니라 하나의 프리즈마 쿼리로 전부다 업데이트 할 수 있을 것 같네요!!

2024-02-22 05:46 UTC, RightHennessy commented on src/studyroom/dto/studyroomReservation.dto.ts
> +        .sort((a, b) => {
날짜 기준으로 함을 함수이름에 표기해주겟습니다 ~

2024-02-22 05:46 UTC, RightHennessy commented on src/studyroom/payload/studyroomReserve.payload.ts
> +  @Type(() => Number)
number로 받고 싶어서요?

2024-02-22 05:47 UTC, RightHennessy commented on src/studyroom/studyroom.service.ts
> +      UserInfoPayload.from(payload.password),
이렇게가 무슨 뜻일까염?

2024-02-22 05:47 UTC, RightHennessy commented on src/studyroom/studyroom.service.ts
> +    await this.studyroomRepository.cancelReservation(id, payload.cancelReason);
함수 중복이 있었어서 cancelReservation을 없앴습니다 ~

2024-02-22 06:07 UTC, RightHennessy commented on src/studyroom/studyroom.repository.ts
> +  async deleteReservations(userId: string, reservations: ReservationResponse) {
이렇게 했던 이유가 udateMany를 이중으로 사용하지 못해서.. 였습니다 !
(delete할 때 사라진 studyReservation 모두 찾고, 그다음에 이와 연결된 userReservation을 모두 찾아야하기 때문..)
아니면 사라진 reservation 하나당으로 로직을 바꿔볼까요?

2024-02-22 06:17 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +  async deleteReservations(userId: string, reservations: ReservationResponse) {
아앗 그렇다면 이 방법은 어떨까요

1. StudyroomReservation에서 업데이트해야할 애들의 id만 전부 먼저 조회해 온다. (findMany)
2. UserReservation에서 방금 찾아온 StudyroomReservation id들에 해당하는 애들을 전부 업데이트 한다 (updateMany)
3. ReservationSlots에서 방금 찾아온 StudyroomReservation id들에 해당하는 애들을 전부 업데이트 한다 (updateMany)

이렇게 하면 쿼리 3번으로 모두 업데이트할 수 있네용

2024-02-22 06:20 UTC, therealjamesjung commented on src/studyroom/studyroom.service.ts
> +      UserInfoPayload.from(payload.password),
아하 Payload에서 from함수를 쓴 이유가 무엇인가요가 질문입니다

2024-02-22 06:23 UTC, therealjamesjung commented on src/studyroom/dto/studyroomReservation.dto.ts
> +        .sort((a, b) => {
아하 a.date > b.date 이렇게 하면 제대로 동작 안하나요? (잘 모름)

2024-02-22 09:55 UTC, RightHennessy commented on src/studyroom/studyroom.repository.ts
> +  async deleteReservations(userId: string, reservations: ReservationResponse) {
이 쿼리 3번은 한번의 트랜잭션 안에서 수행되어야할까요? 
아직 트랜잭션 한번에 어디까지 해야하는건지 명확한 기준이 없으니 감이 안오네요..

2024-02-23 01:06 UTC, therealjamesjung commented on src/studyroom/studyroom.repository.ts
> +    await this.prismaService.$transaction(async (tx) => {
이거 안에 await들 해야되지 않나용?

2024-02-23 01:47 UTC, therealjamesjung commented
UserController에 보면

```
@ApiCreatedResponse({
    description: '친구 추가 성공',
  })
  @ApiNotFoundResponse({
    description: '존재하지 않는 사용자입니다.',
  })
  @ApiBadRequestResponse({
    description:
      '이미 친구로 등록된 사용자입니다. | 자기 자신을 친구로 등록할 수 없습니다.',
  })

```

이런식으로 Service/Repository 상에서 던지는 에러 메세지들을 스웨거 문서에 명시해달라는 프론트 요청이 있어서 이렇게 명시해놨습니다. 아직 Attendance는 못했는데, 스룸도 이것들 처리 부탁드립니당

2024-02-23 01:51 UTC, therealjamesjung commented
ReposItory에 `getAllStudyrooms` 과 같이 배열을 반환하는 것들은 빈 배열을 반환하면 되지만,
`getStudyroomById`나 `getReservationById`과 같이 ID를 넣고 검색하는 애들은 ID에 해당하는 애들이 없을 때는 NotFoundException을 던져야 합니다 지금은 없는 id를 넣으면 500에러가 뜰꺼에요.

2024-02-23 01:52 UTC, therealjamesjung commented
그리구 Repository에 return타입이 없는 것들이 있는데, 반환값이 없더라도 Promise이긴 해서 `Promise<void>`라고 리턴값 명시해주는게 좋습니당

2024-02-23 01:53 UTC, therealjamesjung commented on src/studyroom/dto/studyroomReservation.dto.ts
>  export class StudyroomReservatoinListDto {
@RightHennessy 이거 안고쳐졌슴당

2024-02-23 01:55 UTC, therealjamesjung commented
진짜 이것들만 해결하면 머지 가시죠!!!! 스룸 하시느라 고생 많았습니다 💯💯💯💯

2024-02-23 09:54 UTC, RightHennessy commented
마지막으로 다시 한번 확인하고 승인부탁드립니다ㅏ

2024-02-23 10:23 UTC, therealjamesjung approved these changes
백엔드를 처음 하는데, 저의 팀 매니징 미스로 혼자 너무 큰 단위의 태스크를 맡겨서 (완전한 앱 하나) 많이 힘드셨을텐데 너무 고생 많으셨습니다..

코드나 쿼리들도 전반적으로 잘 짜여져있어서 크게 문제 없을꺼라고 생각합니다!!

2024-02-23 10:23 UTC, merged